# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wanted_pre_onboarding
      MYSQL_USER: backend
      MYSQL_PASSWORD: 2308

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app1:
    depends_on:
      - db
    ports:
      - "8000:3000"
    restart: on-failure
    build: ./app
    hostname: app1
    links:
      - db:mysql

  app2:
    depends_on:
      - db
    ports:
      - "8001:3000"
    restart: on-failure
    build: ./app
    hostname: app2
    links:
      - db:mysql

  nginx:
    depends_on:
      - app1
      - app2
    ports:
      - '80:80'
    build: nginx
