# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wanted_pre_onboarding
      MYSQL_USER: backend
      MYSQL_PASSWORD: 2308

  app:
    depends_on:
      - db
    ports:
      - "8000:3000"
    restart: on-failure
    build: ./app
    hostname: app
    links:
      - db:mysql
