# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wanted_pre_onboarding
      MYSQL_USER: backend
      MYSQL_PASSWORD: 2308

  app:
    depends_on:
      - db
    ports:
      - "8000:3000"
    restart: always
    build: .
    environment:
      SERVICE_NAME: 'pre_onboarding_backend'
      NODE_ENV: 'development'
      PORT: 3000
      MYSQL_OPTIONS_HOST: db
      MYSQL_DATABASE: wanted_pre_onboarding
      MYSQL_USERNAME: backend
      MYSQL_PASSWORD: 2308
      MYSQL_OPTIONS_DIALECT: 'mysql'
      MYSQL_OPTIONS_POOL_MAX: 5
      MYSQL_OPTIONS_POOL_MIN: 0
      MYSQL_OPTIONS_POOL_IDLE: 10000
      MYSQL_OPTIONS_LOGGING: 0
      JWT_SECRET_KEY: 'good_to_go'
